# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: test/v2/test.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Test(betterproto.Message):
    name: str = betterproto.string_field(1, group="_name")
    id: int = betterproto.int32_field(2, group="_id")
    email: str = betterproto.string_field(3, group="_email")
