// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: abc/v1/abc.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Abc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  *string `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Id    *int32  `protobuf:"varint,2,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Email *string `protobuf:"bytes,3,opt,name=email,proto3,oneof" json:"email,omitempty"` // common.v1.ABC abc = 4;
}

func (x *Abc) Reset() {
	*x = Abc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_abc_v1_abc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Abc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Abc) ProtoMessage() {}

func (x *Abc) ProtoReflect() protoreflect.Message {
	mi := &file_abc_v1_abc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Abc.ProtoReflect.Descriptor instead.
func (*Abc) Descriptor() ([]byte, []int) {
	return file_abc_v1_abc_proto_rawDescGZIP(), []int{0}
}

func (x *Abc) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Abc) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *Abc) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

var File_abc_v1_abc_proto protoreflect.FileDescriptor

var file_abc_v1_abc_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x62, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x62, 0x63, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x61, 0x62, 0x63, 0x2e, 0x76, 0x31, 0x22, 0x68, 0x0a, 0x03, 0x41, 0x62,
	0x63, 0x12, 0x17, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x13, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x02, 0x69, 0x64, 0x88, 0x01, 0x01, 0x12,
	0x19, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02,
	0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x69, 0x64, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x42, 0x57, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x62, 0x63, 0x2e,
	0x76, 0x31, 0x42, 0x08, 0x41, 0x62, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x06,
	0x61, 0x62, 0x63, 0x2f, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x41, 0x58, 0x58, 0xaa, 0x02, 0x06, 0x41,
	0x62, 0x63, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x06, 0x41, 0x62, 0x63, 0x5c, 0x56, 0x31, 0xe2, 0x02,
	0x12, 0x41, 0x62, 0x63, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0xea, 0x02, 0x07, 0x41, 0x62, 0x63, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_abc_v1_abc_proto_rawDescOnce sync.Once
	file_abc_v1_abc_proto_rawDescData = file_abc_v1_abc_proto_rawDesc
)

func file_abc_v1_abc_proto_rawDescGZIP() []byte {
	file_abc_v1_abc_proto_rawDescOnce.Do(func() {
		file_abc_v1_abc_proto_rawDescData = protoimpl.X.CompressGZIP(file_abc_v1_abc_proto_rawDescData)
	})
	return file_abc_v1_abc_proto_rawDescData
}

var file_abc_v1_abc_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_abc_v1_abc_proto_goTypes = []interface{}{
	(*Abc)(nil), // 0: abc.v1.Abc
}
var file_abc_v1_abc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_abc_v1_abc_proto_init() }
func file_abc_v1_abc_proto_init() {
	if File_abc_v1_abc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_abc_v1_abc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Abc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_abc_v1_abc_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_abc_v1_abc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_abc_v1_abc_proto_goTypes,
		DependencyIndexes: file_abc_v1_abc_proto_depIdxs,
		MessageInfos:      file_abc_v1_abc_proto_msgTypes,
	}.Build()
	File_abc_v1_abc_proto = out.File
	file_abc_v1_abc_proto_rawDesc = nil
	file_abc_v1_abc_proto_goTypes = nil
	file_abc_v1_abc_proto_depIdxs = nil
}
