# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: abc/v1/abc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61\x62\x63/v1/abc.proto\x12\x06\x61\x62\x63.v1\"h\n\x03\x41\x42\x43\x12\x17\n\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x13\n\x02id\x18\x02 \x01(\x05H\x01R\x02id\x88\x01\x01\x12\x19\n\x05\x65mail\x18\x03 \x01(\tH\x02R\x05\x65mail\x88\x01\x01\x42\x07\n\x05_nameB\x05\n\x03_idB\x08\n\x06_emailBO\n\ncom.abc.v1B\x08\x41\x62\x63ProtoP\x01\xa2\x02\x03\x41XX\xaa\x02\x06\x41\x62\x63.V1\xca\x02\x06\x41\x62\x63\\V1\xe2\x02\x12\x41\x62\x63\\V1\\GPBMetadata\xea\x02\x07\x41\x62\x63::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'abc.v1.abc_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\ncom.abc.v1B\010AbcProtoP\001\242\002\003AXX\252\002\006Abc.V1\312\002\006Abc\\V1\342\002\022Abc\\V1\\GPBMetadata\352\002\007Abc::V1'
  _globals['_ABC']._serialized_start=28
  _globals['_ABC']._serialized_end=132
# @@protoc_insertion_point(module_scope)
